// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Aris Rhiannon
//
// TOP_NAMES: the typosquat-target reference set used by `WG-TYPOSQUAT`.
//
// The list is loaded from `data/top-names.json`, which is produced by
// `scripts/refresh-top-names.ts` from ecosyste.ms's public "most depended on"
// view of the npm registry, sorted descending by dependent-package count.
//
// Provenance and the date the list was last regenerated are recorded in the
// JSON file's top-level fields (`source`, `fetchedAt`). Re-run
// `bun run scripts/refresh-top-names.ts` (or `wormguard refresh-top-names`)
// to regenerate.
//
// We keep a small fallback baked in so the module still works for users who
// installed wormguard without the bundled data file.

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA_PATH = join(HERE, "..", "data", "top-names.json");

const FALLBACK: string[] = [
  "react", "react-dom", "lodash", "express", "axios", "typescript", "vue",
  "next", "webpack", "rollup", "vite", "esbuild", "eslint", "prettier",
  "jest", "mocha", "chai", "vitest", "tslib", "moment", "date-fns", "dayjs",
  "uuid", "dotenv", "chalk", "commander", "debug", "yargs", "minimist",
  "glob", "fs-extra", "rimraf", "cross-env", "semver", "chokidar", "ts-node",
];

interface TopNamesFile {
  version: number;
  source: string;
  fetchedAt: string;
  count: number;
  names: string[];
}

function load(): { names: string[]; provenance: { source: string; fetchedAt: string } | null } {
  if (!existsSync(DATA_PATH)) {
    return { names: FALLBACK, provenance: null };
  }
  try {
    const json = JSON.parse(readFileSync(DATA_PATH, "utf8")) as TopNamesFile;
    if (!Array.isArray(json.names) || json.names.length === 0) {
      return { names: FALLBACK, provenance: null };
    }
    return {
      names: json.names,
      provenance: { source: json.source, fetchedAt: json.fetchedAt },
    };
  } catch {
    return { names: FALLBACK, provenance: null };
  }
}

const loaded = load();

/** Curated list of widely-used npm package names used as typosquat reference
 *  targets. Loaded from `data/top-names.json` (generated by
 *  scripts/refresh-top-names.ts) with a small built-in fallback. */
export const TOP_NAMES: string[] = loaded.names;

/** Provenance metadata: where the list came from and when it was last
 *  regenerated. `null` when running off the built-in fallback. */
export const TOP_NAMES_PROVENANCE: { source: string; fetchedAt: string } | null =
  loaded.provenance;
